POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "username": "mailfrreg@yandex.ru",
  "password": "password"
}

###
#{"authenticationToken":"e7ab9067-ec1a-42a7-be52-fa97a797e843"}

POST http://localhost:8080/api/authentication
Content-Type: application/json

{
  "username": "mailfrreg@yandex.ru",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("authenticationToken", response.body.authenticationToken)
});
%}

###

GET http://localhost:8080/api/expenses/kind
Accept: application/json
X-Chat-Token: e7ab9067-ec1a-42a7-be52-fa97a797e843

###

GET http://localhost:8080/api/expenses/kind
Accept: application/json
X-Chat-Token: 1ee2f234-070a-4451-b9e6-5d2f316ee705

###

POST http://localhost:8080/api/expenses/kind
Content-Type: application/json
X-Chat-Token: 1d982c87-8963-4bc5-893d-526e87eb452d

{
  "name": "Кафе",
  "purpose": "SERVICE"
}

###

GET http://localhost:8080/api/expenses
Accept: application/json
X-Chat-Token: 9c0f1e18-68d8-4d1e-9658-d9a7b1fcb8e8

###

POST http://localhost:8080/api/expenses
Content-Type: application/json
X-Chat-Token: eb7bb8f6-5977-4626-9c28-36aea8076707

{
  "name": "Пятерочка",
  "expensesKind": "Супермаркет",
  "description": "test",
  "cost": 30100,
  "paymentType": true,
  "created": 1569085390
}

###

POST http://localhost:8080/api/expenses
Content-Type: application/json
X-Chat-Token: 9c0f1e18-68d8-4d1e-9658-d9a7b1fcb8e8

{
  "name": "Трата",
  "expensesKind": "FOOD",
  "description": "test",
  "cost": 600,
  "paymentType": true,
  "created": 1569085390
}

###

GET http://localhost:8080/api/expenses/period?dateFrom=01.02.2020
Content-Type: application/json
X-Chat-Token: 5c1ce583-d68e-4467-8ea6-06402e1a1070

###

POST http://localhost:8080/api/expenses/calculate
Content-Type: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

{
  "filterBy": "Пятерочка",
  "period": {
    "from": "1569085390",
    "till": "1569085392"
  }
}

###

POST http://localhost:8080/api/expenses/calculate
Content-Type: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

{
  "filterBy": "FOOD",
  "period": {
    "from": "1569085390",
    "till": "1569085392"
  }
}

###

POST http://localhost:8080/api/expenses/calculate
Content-Type: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

{
  "filterBy": "FOOD",
  "details": true,
  "period": {
    "from": "1970-01-19 06:51:25.389000",
    "till": "1970-01-19 06:51:25.390000"
  }
}

###

POST http://localhost:8080/api/income
Content-Type: application/json
X-Chat-Token: 18336a9c-442d-46d8-9bcb-0d9612e8544b

{
  "name": "Зачисление зарплаты",
  "category": "SALARY",
  "cost": "4000000"
}

###

GET http://localhost:8080/api/income?from=&till=
Accept: application/json
X-Chat-Token: 18336a9c-442d-46d8-9bcb-0d9612e8544b

###