POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "username": "mailfrreg@yandex.ru",
  "password": "password"
}

###

POST http://localhost:8080/api/authentication
Content-Type: application/json

{
  "username": "mailfrreg@yandex.ru",
  "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("authenticationToken", response.body.authenticationToken)
});
%}

###

GET http://localhost:8080/api/expenses/kind
Accept: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

###

POST http://localhost:8080/api/expenses/kind
Content-Type: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

{
  "name": "Супермаркет2",
  "purpose": "FOOD"
}

###

GET http://localhost:8080/api/expenses
Accept: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

###

POST http://localhost:8080/api/expenses
Content-Type: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

{
  "name": "Пятерочка",
  "expensesKind": "Супермаркет",
  "description": "test",
  "cost": 30100,
  "paymentType": true,
  "created": 1569085390
}

###

POST http://localhost:8080/api/expenses/calculate
Content-Type: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

{
  "filterBy": "Пятерочка",
  "period": {
    "from": "1569085390",
    "till": "1569085392"
  }
}

###

POST http://localhost:8080/api/expenses/calculate
Content-Type: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

{
  "filterBy": "FOOD",
  "period": {
    "from": "1569085390",
    "till": "1569085392"
  }
}

###

POST http://localhost:8080/api/expenses/calculate
Content-Type: application/json
X-Chat-Token: f2e254cc-e23a-4537-b502-457c2301af5a

{
  "filterBy": "FOOD",
  "details": true,
  "period": {
    "from": "1970-01-19 06:51:25.389000",
    "till": "1970-01-19 06:51:25.390000"
  }
}

###

POST http://localhost:8080/api/income
Content-Type: application/json
X-Chat-Token: 18336a9c-442d-46d8-9bcb-0d9612e8544b

{
  "name": "Зачисление зарплаты",
  "category": "SALARY",
  "cost": "4000000"
}

###

GET http://localhost:8080/api/income?from=&till=
Accept: application/json
X-Chat-Token: 18336a9c-442d-46d8-9bcb-0d9612e8544b

###