jwt.super-secter: super

server:
  port: ${PORT:8083}
spring:
  application:
    name: '@project.name@'
  datasource:
    url: ${DATABASE_URI}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10