/*
 * This file is generated by jOOQ.
 */
package ru.multiplier.dao.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.multiplier.dao.jooq.tables.ExpenseCategory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpenseCategoryRecord extends UpdatableRecordImpl<ExpenseCategoryRecord> implements Record3<UUID, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.expense_category.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.expense_category.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.expense_category.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.expense_category.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.expense_category.category</code>.
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.expense_category.category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ExpenseCategory.EXPENSE_CATEGORY.ID;
    }

    @Override
    public Field<String> field2() {
        return ExpenseCategory.EXPENSE_CATEGORY.NAME;
    }

    @Override
    public Field<String> field3() {
        return ExpenseCategory.EXPENSE_CATEGORY.CATEGORY;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCategory();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCategory();
    }

    @Override
    public ExpenseCategoryRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ExpenseCategoryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ExpenseCategoryRecord value3(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public ExpenseCategoryRecord values(UUID value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExpenseCategoryRecord
     */
    public ExpenseCategoryRecord() {
        super(ExpenseCategory.EXPENSE_CATEGORY);
    }

    /**
     * Create a detached, initialised ExpenseCategoryRecord
     */
    public ExpenseCategoryRecord(UUID id, String name, String category) {
        super(ExpenseCategory.EXPENSE_CATEGORY);

        setId(id);
        setName(name);
        setCategory(category);
    }
}
