/*
 * This file is generated by jOOQ.
 */
package ru.multiplier.dao.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.multiplier.dao.jooq.tables.TelegramUser;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TELEGRAM_USER_ID_IDX = Internal.createIndex(DSL.name("telegram_user_id_idx"), TelegramUser.TELEGRAM_USER, new OrderField[] { TelegramUser.TELEGRAM_USER.TELEGRAM_USER_ID }, true);
}
