/*
 * This file is generated by jOOQ.
 */
package ru.multiplier.dao.jooq;


import ru.multiplier.dao.jooq.tables.ExpenseCategory;
import ru.multiplier.dao.jooq.tables.TelegramUser;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.expense_category</code>.
     */
    public static final ExpenseCategory EXPENSE_CATEGORY = ExpenseCategory.EXPENSE_CATEGORY;

    /**
     * The table <code>public.telegram_user</code>.
     */
    public static final TelegramUser TELEGRAM_USER = TelegramUser.TELEGRAM_USER;
}
